APP_ENV=local
APP_KEY=base64:GUlrWeXE1QDcCY7ln3bKxtj9gKMGRYA0TFeDfZS3rmo=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://tournapp.dev

#DB_CONNECTION=pgsql
#DB_HOST=dev-pg.tournapps.com
#DB_PORT=5432
#DB_DATABASE=dev_tournapps_db
#DB_USERNAME=dev_tournapps
#DB_PASSWORD=J7a6e%B=M|)k

DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=test_tournapps
DB_USERNAME=postgres
DB_PASSWORD=gkxim@123

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

TOURN_APP_DOMAIN=http://dev.tournapps.com
